### ISSUE TITLE
Need a prototype website design

### ISSUE THREAD

**Issue by congdon** [OpenMaine/campaign-finance#3]
Alex has been working on Tableau visualizations that will get added into a website (e.g., as an HTML embed tag).

1. Just need webpage structure to see what this will look like.

2. The website proper will need design

3. The website proper will need a lot of words to explain the site, what the financial reporting process is in Portland, the source of the data, etc.

**Comment by congdon** [comment]
"A website" has been created, and is ready for someone to "design" it.

Also needed: words. We need to think about what information is needed and write that info.

**Comment by shannonmcharg** [comment]
If you can walk us through what you have so far in terms of the data and visualizations in Thursday's meeting, I can work on this during the meeting.

**Comment by congdon** [comment]
The sort of outline website is there in the repo.

We have a bunch of new people; if any are 'web designers' and have energy, we should maybe step aside and let that happen?

Alex is in charge of visualizations, but I couldn't figure out how to embed them in the html (just from tableau, but I think he needs to grant permissions for it or something). He has not yet replied. But his initial work is linked into the slack channel.

**Comment by congdon** [comment]
FYI: Amy has picked this up...
