### ISSUE TITLE
need to know how to embed tableau visualization in HTML

### ISSUE THREAD

**Issue by congdon** [OpenMaine/campaign-finance#7]
I think you might need to grant permissions for this to happen, Alex. I couldn't figure it out.

**Comment by AlexPixley** [comment]
This is the embed code:
<div class='tableauPlaceholder' id='viz1568940316437' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Op&#47;OpenMaine&#47;Histogram&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='OpenMaine&#47;Histogram' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Op&#47;OpenMaine&#47;Histogram&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1568940316437');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Comment by AlexPixley** [comment]
That didn't work as expected, and I don't see how to add an attachment, so I'll just email it to Clare.

**Comment by congdon** [comment]
Works! Thank you!
